# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d827226833036d80d416c99dcb1105d580c1f096ab26550bdd59851e6eb5c1bde44d727544aedd6e6a37cd670dfa691773d94d6072796c6aef160ce23b5673f

test:
  secret_key_base: 8a5a1e706c9bc714b8846ac7e8a707e4a7cb421b14a90a482318224a702382464dba2ff50918ab2b324a1a9ebd552572d3eef1734be4672d560e8ffef8d4e61c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
